version: "3"

services:
  web:
    build: ./creatify
    ports:
      - "8555:8000"
    volumes:
      - ./creatify:/var/www/html/creatify # 挂载项目代码
    restart: always
    tty: true
    stdin_open: true
